name: Update Predictions and Backtest

on:
  workflow_dispatch:  # allows manual trigger

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set OpenAI API Key
      run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV

    - name: Run Predictor
      run: python predictor_upgrade.py

    - name: Run Backtester
      run: python backtesting_script.py

    - name: Commit Updated Data
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add predictions.json backtest_results.csv
        git commit -m "Auto-update: predictions and backtest results"
        git push
