name: Update Predictions and Backtest

on:
  workflow_dispatch:  # Trigger manually from GitHub Actions tab

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run predictor script
        run: python predictor_upgrade.py

      - name: Run backtesting script
        run: python backtesting_script.py

      - name: Commit and push updated files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add predictions.json backtest_results.csv
          git commit -m "Auto-update: predictions and backtest results" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/DMCHERy/dmchery.github.io.git HEAD:main
